# Generated by Django 4.2.16 on 2025-04-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['number'], 'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['name'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['number'], 'verbose_name': 'Параграф', 'verbose_name_plural': 'Параграфы'},
        ),
    ]
